Update

diff --git a/.github/workflows/ProgramCodeConvention.yml b/.github/workflows/ProgramCodeConvention.yml
--- a/.github/workflows/ProgramCodeConvention.yml
+++ b/.github/workflows/ProgramCodeConvention.yml
@@ -12,15 +12,24 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Run Pylint installation
+      - name: Install pylint
         run: |
           sudo apt-get update
           pip install pylint
 
-      - name: Check code conventions with pylint
+      - name: Select file to check
+        id: select_file
         run: |
-          echo "Running Pylint..."
-          pylint ProgramCode.py || exit 1
-          
+          if [ -f ProgramCodeModified.py ]; then
+            echo "FILE=ProgramCodeModified.py" >> $GITHUB_OUTPUT
+          elif [ -f ProgramCode.py ]; then
+            echo "FILE=ProgramCode.py" >> $GITHUB_OUTPUT
+          else
+            echo "No program code file found → FAIL"
+            exit 1
           fi
-          echo "Code conventions OK"
+
+      - name: Run pylint
+        run: |
+          echo "Running pylint on ${{ steps.select_file.outputs.FILE }}..."
+          pylint ${{ steps.select_file.outputs.FILE }} || exit 1
