Update

diff --git a/.github/workflows/ProgramCodeConvention.yml b/.github/workflows/ProgramCodeConvention.yml
--- a/.github/workflows/ProgramCodeConvention.yml
+++ b/.github/workflows/ProgramCodeConvention.yml
@@ -25,9 +25,11 @@ jobs:
 
       - name: Run ESLint
         run: |
-          if [ -f program_code_modified.js ]; then
-            FILE="program_code_modified.js"
-          else
+          if [ -f ProgramCode.js ]; then
             FILE="ProgramCode.js"
+          else
+            echo "No JS code file found → FAIL"
+            exit 1
           fi
+          
           npx eslint "$FILE"
